//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.
//


package com.picdora;

import android.content.Context;

public final class CategoryListAdapter_
    extends CategoryListAdapter
{

    private Context context_;

    private CategoryListAdapter_(Context context) {
        context_ = context;
        init_();
    }

    public static CategoryListAdapter_ getInstance_(Context context) {
        return new CategoryListAdapter_(context);
    }

    private void init_() {
        context = context_;
        initAdapter();
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
