//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.picdora;

import android.app.Activity;
import android.content.Context;
import android.widget.CheckBox;
import android.widget.TextView;
import com.picdora.R.id;
import com.picdora.R.layout;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class CategoryItemView_
    extends CategoryItemView
{

    private Context context_;
    private boolean mAlreadyInflated_ = false;

    public CategoryItemView_(Context context) {
        super(context);
        init_();
    }

    private void init_() {
        context_ = getContext();
        if (context_ instanceof Activity) {
            Activity activity = ((Activity) context_);
        }
    }

    private void afterSetContentView_() {
        categoryName = ((TextView) findViewById(id.categoryName));
        checkBox = ((CheckBox) findViewById(id.checkBox));
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!mAlreadyInflated_) {
            mAlreadyInflated_ = true;
            inflate(getContext(), layout.category_list_item, this);
            afterSetContentView_();
        }
        super.onFinishInflate();
    }

    public static CategoryItemView build(Context context) {
        CategoryItemView_ instance = new CategoryItemView_(context);
        instance.onFinishInflate();
        return instance;
    }

}
