//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.
//


package com.picdora;

import android.content.Context;

public final class ChannelHelper_
    extends ChannelHelper
{

    private Context context_;

    private ChannelHelper_(Context context) {
        context_ = context;
        init_();
    }

    public static ChannelHelper_ getInstance_(Context context) {
        return new ChannelHelper_(context);
    }

    private void init_() {
        context = context_;
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
