//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.picdora;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.KeyEvent;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.AdapterView;
import android.widget.AdapterView.OnItemClickListener;
import android.widget.ListView;
import com.googlecode.androidannotations.api.SdkVersionHelper;
import com.picdora.R.layout;
import com.picdora.models.Channel;

public final class ChannelSelectionActivity_
    extends ChannelSelectionActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.activity_channel_selection);
    }

    private void init_(Bundle savedInstanceState) {
        adapter = ChannelListAdapter_.getInstance_(this);
    }

    private void afterSetContentView_() {
        channelList = ((ListView) findViewById(com.picdora.R.id.channelList));
        {
            AdapterView<?> view = ((AdapterView<?> ) findViewById(com.picdora.R.id.channelList));
            if (view!= null) {
                view.setOnItemClickListener(new OnItemClickListener() {


                    @Override
                    public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                        channelListItemClicked(((Channel) parent.getAdapter().getItem(position)));
                    }

                }
                );
            }
        }
        ((ChannelListAdapter_) adapter).afterSetContentView_();
        bindAdapter();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static ChannelSelectionActivity_.IntentBuilder_ intent(Context context) {
        return new ChannelSelectionActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, ChannelSelectionActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public ChannelSelectionActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
