//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.picdora;

import android.content.Context;

public final class ChannelListAdapter_
    extends ChannelListAdapter
{

    private Context context_;

    private ChannelListAdapter_(Context context) {
        context_ = context;
        init_();
    }

    public static ChannelListAdapter_ getInstance_(Context context) {
        return new ChannelListAdapter_(context);
    }

    private void init_() {
        context = context_;
        initAdapter();
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
