//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.
//


package com.picdora;

import android.content.Context;
import android.content.SharedPreferences;
import org.androidannotations.api.sharedpreferences.EditorHelper;
import org.androidannotations.api.sharedpreferences.LongPrefEditorField;
import org.androidannotations.api.sharedpreferences.LongPrefField;
import org.androidannotations.api.sharedpreferences.SharedPreferencesHelper;

public final class PicdoraPreferences_
    extends SharedPreferencesHelper
{

    private Context context_;

    public PicdoraPreferences_(Context context) {
        super(context.getSharedPreferences((getLocalClassName(context)+"_PicdoraPreferences"), 0));
        this.context_ = context;
    }

    public PicdoraPreferences_.PicdoraPreferencesEditor_ edit() {
        return new PicdoraPreferences_.PicdoraPreferencesEditor_(getSharedPreferences());
    }

    private static String getLocalClassName(Context context) {
        String packageName = context.getPackageName();
        String className = context.getClass().getName();
        int packageLen = packageName.length();
        if (((!className.startsWith(packageName))||(className.length()<= packageLen))||(className.charAt(packageLen)!= '.')) {
            return className;
        }
        return className.substring((packageLen + 1));
    }

    public LongPrefField lastUpdated() {
        return longField("lastUpdated", 0L);
    }

    public final static class PicdoraPreferencesEditor_
        extends EditorHelper<PicdoraPreferences_.PicdoraPreferencesEditor_>
    {


        PicdoraPreferencesEditor_(SharedPreferences sharedPreferences) {
            super(sharedPreferences);
        }

        public LongPrefEditorField<PicdoraPreferences_.PicdoraPreferencesEditor_> lastUpdated() {
            return longField("lastUpdated");
        }

    }

}
