//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.picdora;


public final class PicdoraApp_
    extends PicdoraApp
{

    private static PicdoraApp INSTANCE_;

    public static PicdoraApp getInstance() {
        return INSTANCE_;
    }

    /**
     * Visible for testing purposes
     * 
     */
    public static void setForTesting(PicdoraApp application) {
        INSTANCE_ = application;
    }

    @Override
    public void onCreate() {
        INSTANCE_ = this;
        init_();
        super.onCreate();
    }

    private void init_() {
        mImageUpdater = ImageUpdater_.getInstance_(this);
    }

}
