//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.picdora.player;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ProgressBar;
import com.picdora.R.layout;
import net.frakbot.imageviewex.ImageViewNext;
import uk.co.senab.photoview.PhotoView;

public final class ImageSwipeFragment_
    extends ImageSwipeFragment
{

    private View contentView_;

    private void init_(Bundle savedInstanceState) {
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void afterSetContentView_() {
        mProgress = ((ProgressBar) findViewById(com.picdora.R.id.progress));
        mPhotoView = ((PhotoView) findViewById(com.picdora.R.id.image));
        mGifView = ((ImageViewNext) findViewById(com.picdora.R.id.gif));
        addImage();
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.swipable_image, container, false);
        }
        return contentView_;
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        afterSetContentView_();
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    public static ImageSwipeFragment_.FragmentBuilder_ builder() {
        return new ImageSwipeFragment_.FragmentBuilder_();
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public ImageSwipeFragment build() {
            ImageSwipeFragment_ fragment_ = new ImageSwipeFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
